/* GENERATED by tools/gen_contract_ts.py — DO NOT EDIT.
 * Source of truth: engine/contract.py
 * Regenerate: python -m tools.gen_contract_ts
 * Regenerate-and-write: python -m tools.gen_contract_ts --write
 */
import { z } from "zod";

/** Open vocabularies: the backend may add kinds; the UI shows a default glyph. */
export const REASON_KINDS = ["zoom", "unknown_day", "unknown_band", "out_of_scope", "unrecognized", "unreadable", "stage_failed", "in_zone", "below_min", "coverage_gate"] as const;
export const FAILURE_KINDS = ["gate_rejected", "input_unreadable", "stage_failed"] as const;
export const STAGE_NAMES = ["input", "anchor", "segment", "classify", "depth", "portion", "nutrition", "compliance"] as const;
/** Closed: every verdict/stage value is known today. */
export const VERDICTS = ["PASS", "BORDERLINE", "FAIL", "cannot_verify", "out_of_scope"] as const;

export type Verdict = (typeof VERDICTS)[number];
export type StageName = (typeof STAGE_NAMES)[number];
export type ReasonKind = (typeof REASON_KINDS)[number] | (string & {});
export type FailureKind = (typeof FAILURE_KINDS)[number] | (string & {});

export const reasonSchema = z.object({
  kind: z.string(),
  text: z.string(),
});
export type Reason = z.infer<typeof reasonSchema>;

export const failureSchema = z.object({
  kind: z.string(),
  stage: z.enum(STAGE_NAMES),
  error: z.string(),
});
export type Failure = z.infer<typeof failureSchema>;

export const policySchema = z.object({
  pass_p: z.number(),
  fail_p: z.number(),
  pass_min: z.number(),
  fail_min: z.number(),
  anchor_prior_cap: z.number(),
  base_table_prior: z.number(),
  quality_degraded: z.number(),
  lint_min_side_px: z.number(),
  policy_version: z.string(),
});
export type Policy = z.infer<typeof policySchema>;

export const lintSchema = z.object({
  digital_zoom: z.number().nullable(),
  focal_mm: z.number().nullable(),
  min_side_px: z.number(),
  resolution_ok: z.boolean(),
  notes: z.array(z.string()),
});
export type Lint = z.infer<typeof lintSchema>;

export const anchorSchema = z.object({
  method: z.string().nullable(),
  tier: z.string().nullable(),
  cm_per_px: z.number().nullable(),
  interval: z.tuple([z.number().nullable(), z.number().nullable()]).nullable(),
  tilt_deg: z.number().nullable(),
  reason: z.string().nullable(),
  depth_scale_factor: z.number().optional(),
  depth_scale_source: z.string().optional(),
});
export type AnchorBlock = z.infer<typeof anchorSchema>;

export const segmentationSchema = z.object({
  strategy: z.string().nullable(),
  sam_score: z.number().nullable(),
  area_frac: z.number().nullable(),
  n_candidates: z.number().nullable(),
});
export type SegmentationBlock = z.infer<typeof segmentationSchema>;

export const classificationSchema = z.object({
  dish: z.string().nullable(),
  confidence: z.number().nullable(),
  method: z.string().nullable(),
  match_score: z.number().nullable(),
  reason: z.string().nullable(),
});
export type ClassificationBlock = z.infer<typeof classificationSchema>;

export const dishSchema = z.object({
  id: z.string(),
  display_name: z.string().nullable(),
  day: z.string(),
  band: z.string(),
  serving_style: z.string().nullable(),
  on_day: z.boolean(),
  nutrition_source: z.string().nullable(),
});
export type DishBlock = z.infer<typeof dishSchema>;

export const portionSchema = z.object({
  grams: z.number(),
  volume_ml: z.number(),
  density_eff: z.number(),
  components_g: z.record(z.string(), z.number()),
  base_method: z.string(),
  scale_tier: z.string(),
  mean_h_mm: z.number(),
  area_cm2: z.number(),
  sigma_grams_rel: z.number(),
  sigma_rel: z.record(z.string(), z.number()),
  flags: z.array(z.string()),
});
export type PortionBlock = z.infer<typeof portionSchema>;

export const nutrientSummarySchema = z.object({
  mean: z.number(),
  sd: z.number(),
  p05: z.number(),
  p50: z.number(),
  p95: z.number(),
  interval_90: z.tuple([z.number(), z.number()]),
});
export type NutrientSummary = z.infer<typeof nutrientSummarySchema>;

export const nutritionSchema = z.object({
  kcal: nutrientSummarySchema,
  protein_g: nutrientSummarySchema,
  grams: nutrientSummarySchema,
  n: z.number(),
  seed: z.number(),
  diagnostics: z.record(z.string(), z.unknown()),
  assumed_nutrients: z.array(z.string()),
  wider_ranges: z.boolean(),
});
export type NutritionBlock = z.infer<typeof nutritionSchema>;

export const coverageSchema = z.object({
  score: z.number(),
  factors: z.record(z.string(), z.number()),
  pass_min: z.number(),
  fail_min: z.number(),
});
export type CoverageBlock = z.infer<typeof coverageSchema>;

export const advisorySchema = z.object({
  sodium_salt: z
    .object({
      direction: z.string().nullable().optional(),
      primary_g: z.number().nullable().optional(),
      upper_g: z.number().nullable().optional(),
      note: z.string().nullable().optional(),
    })
    .nullable(),
  note: z.string().nullable().optional(),
});
export type AdvisoryBlock = z.infer<typeof advisorySchema>;

export const nutrientRowSchema = z.object({
  min: z.number(),
  p_at_or_above_min: z.number(),
  mean: z.number(),
  interval_90: z.tuple([z.number(), z.number()]),
  headroom_at_interval_low: z.number(),
});
export type NutrientRow = z.infer<typeof nutrientRowSchema>;

export const complianceSchema = z.object({
  day: z.string().nullable(),
  band: z.string(),
  probs: z.record(z.string(), z.number()),
  nutrients: z.record(z.string(), nutrientRowSchema),
});
export type ComplianceBlock = z.infer<typeof complianceSchema>;

export const analysisSchema = z.object({
  verdict: z.enum(VERDICTS),
  reasons: z.array(reasonSchema),
  failures: z.array(failureSchema),
  lint: lintSchema.nullable(),
  anchor: anchorSchema.nullable(),
  segmentation: segmentationSchema.nullable(),
  classification: classificationSchema.nullable(),
  dish: dishSchema.nullable(),
  portion: portionSchema.nullable(),
  nutrition: nutritionSchema.nullable(),
  coverage: coverageSchema.nullable(),
  assumptions: z.array(z.string()),
  advisory: advisorySchema.nullable(),
  compliance: complianceSchema.nullable(),
  model_versions: z.record(z.string(), z.string()),
  policy: policySchema,
});
export type Analysis = z.infer<typeof analysisSchema>;
