"""Generate frontend/src/types/contract.gen.ts from engine.contract.

The Python contract owns the wire shape; this script renders the Zod schema
the frontend decodes with. pytest (tests/test_contract_gen.py) regenerates
into a temp buffer and fails if the committed file is stale — the Zod schema
is never stricter than the wire (kinds open, verdict/stage closed).

Regenerate:  python -m tools.gen_contract_ts
"""
from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from engine.contract import FailureKind, Policy, ReasonKind, Stage  # noqa: E402

OUT_PATH = _ROOT / "frontend" / "src" / "types" / "contract.gen.ts"


def _literals(values) -> str:
    return ", ".join(f'"{v}"' for v in values)


def generate() -> str:
    reason_kinds = _literals(k.value for k in ReasonKind)
    failure_kinds = _literals(k.value for k in FailureKind)
    stages = _literals(s.value for s in Stage)
    verdicts = _literals(Verdict for Verdict in
                         ("PASS", "BORDERLINE", "FAIL", "cannot_verify",
                          "out_of_scope"))
    numeric_policy = [f.name for f in Policy.__dataclass_fields__.values()
                      if f.name != "policy_version"]

    return f"""/* GENERATED by tools/gen_contract_ts.py — DO NOT EDIT.
 * Source of truth: engine/contract.py
 * Regenerate: python -m tools.gen_contract_ts
 * Regenerate-and-write: python -m tools.gen_contract_ts --write
 */
import {{ z }} from "zod";

/** Open vocabularies: the backend may add kinds; the UI shows a default glyph. */
export const REASON_KINDS = [{reason_kinds}] as const;
export const FAILURE_KINDS = [{failure_kinds}] as const;
export const STAGE_NAMES = [{stages}] as const;
/** Closed: every verdict/stage value is known today. */
export const VERDICTS = [{verdicts}] as const;

export type Verdict = (typeof VERDICTS)[number];
export type StageName = (typeof STAGE_NAMES)[number];
export type ReasonKind = (typeof REASON_KINDS)[number] | (string & {{}});
export type FailureKind = (typeof FAILURE_KINDS)[number] | (string & {{}});

export const reasonSchema = z.object({{
  kind: z.string(),
  text: z.string(),
}});
export type Reason = z.infer<typeof reasonSchema>;

export const failureSchema = z.object({{
  kind: z.string(),
  stage: z.enum(STAGE_NAMES),
  error: z.string(),
}});
export type Failure = z.infer<typeof failureSchema>;

export const policySchema = z.object({{
  {", ".join(f"{n}: z.number()" for n in numeric_policy).replace(", ", ",\n  ")},
  policy_version: z.string(),
}});
export type Policy = z.infer<typeof policySchema>;

export const lintSchema = z.object({{
  digital_zoom: z.number().nullable(),
  focal_mm: z.number().nullable(),
  min_side_px: z.number(),
  resolution_ok: z.boolean(),
  notes: z.array(z.string()),
}});
export type Lint = z.infer<typeof lintSchema>;

export const anchorSchema = z.object({{
  method: z.string().nullable(),
  tier: z.string().nullable(),
  cm_per_px: z.number().nullable(),
  interval: z.tuple([z.number().nullable(), z.number().nullable()]).nullable(),
  tilt_deg: z.number().nullable(),
  reason: z.string().nullable(),
  depth_scale_factor: z.number().optional(),
  depth_scale_source: z.string().optional(),
}});
export type AnchorBlock = z.infer<typeof anchorSchema>;

export const segmentationSchema = z.object({{
  strategy: z.string().nullable(),
  sam_score: z.number().nullable(),
  area_frac: z.number().nullable(),
  n_candidates: z.number().nullable(),
}});
export type SegmentationBlock = z.infer<typeof segmentationSchema>;

export const classificationSchema = z.object({{
  dish: z.string().nullable(),
  confidence: z.number().nullable(),
  method: z.string().nullable(),
  match_score: z.number().nullable(),
  reason: z.string().nullable(),
}});
export type ClassificationBlock = z.infer<typeof classificationSchema>;

export const dishSchema = z.object({{
  id: z.string(),
  display_name: z.string().nullable(),
  day: z.string(),
  band: z.string(),
  serving_style: z.string().nullable(),
  on_day: z.boolean(),
  nutrition_source: z.string().nullable(),
}});
export type DishBlock = z.infer<typeof dishSchema>;

export const portionSchema = z.object({{
  grams: z.number(),
  volume_ml: z.number(),
  density_eff: z.number(),
  components_g: z.record(z.string(), z.number()),
  base_method: z.string(),
  scale_tier: z.string(),
  mean_h_mm: z.number(),
  area_cm2: z.number(),
  sigma_grams_rel: z.number(),
  sigma_rel: z.record(z.string(), z.number()),
  flags: z.array(z.string()),
}});
export type PortionBlock = z.infer<typeof portionSchema>;

export const nutrientSummarySchema = z.object({{
  mean: z.number(),
  sd: z.number(),
  p05: z.number(),
  p50: z.number(),
  p95: z.number(),
  interval_90: z.tuple([z.number(), z.number()]),
}});
export type NutrientSummary = z.infer<typeof nutrientSummarySchema>;

export const nutritionSchema = z.object({{
  kcal: nutrientSummarySchema,
  protein_g: nutrientSummarySchema,
  grams: nutrientSummarySchema,
  n: z.number(),
  seed: z.number(),
  diagnostics: z.record(z.string(), z.unknown()),
  assumed_nutrients: z.array(z.string()),
  wider_ranges: z.boolean(),
}});
export type NutritionBlock = z.infer<typeof nutritionSchema>;

export const coverageSchema = z.object({{
  score: z.number(),
  factors: z.record(z.string(), z.number()),
  pass_min: z.number(),
  fail_min: z.number(),
}});
export type CoverageBlock = z.infer<typeof coverageSchema>;

export const advisorySchema = z.object({{
  sodium_salt: z
    .object({{
      direction: z.string().nullable().optional(),
      primary_g: z.number().nullable().optional(),
      upper_g: z.number().nullable().optional(),
      note: z.string().nullable().optional(),
    }})
    .nullable(),
  note: z.string().nullable().optional(),
}});
export type AdvisoryBlock = z.infer<typeof advisorySchema>;

export const nutrientRowSchema = z.object({{
  min: z.number(),
  p_at_or_above_min: z.number(),
  mean: z.number(),
  interval_90: z.tuple([z.number(), z.number()]),
  headroom_at_interval_low: z.number(),
}});
export type NutrientRow = z.infer<typeof nutrientRowSchema>;

export const complianceSchema = z.object({{
  day: z.string().nullable(),
  band: z.string(),
  probs: z.record(z.string(), z.number()),
  nutrients: z.record(z.string(), nutrientRowSchema),
}});
export type ComplianceBlock = z.infer<typeof complianceSchema>;

export const analysisSchema = z.object({{
  verdict: z.enum(VERDICTS),
  reasons: z.array(reasonSchema),
  failures: z.array(failureSchema),
  lint: lintSchema.nullable(),
  anchor: anchorSchema.nullable(),
  segmentation: segmentationSchema.nullable(),
  classification: classificationSchema.nullable(),
  dish: dishSchema.nullable(),
  portion: portionSchema.nullable(),
  nutrition: nutritionSchema.nullable(),
  coverage: coverageSchema.nullable(),
  assumptions: z.array(z.string()),
  advisory: advisorySchema.nullable(),
  compliance: complianceSchema.nullable(),
  model_versions: z.record(z.string(), z.string()),
  policy: policySchema,
}});
export type Analysis = z.infer<typeof analysisSchema>;

export const menuItemSchema = z.looseObject({{
  display_name: z.string().optional(),
  days: z.array(z.string()).optional(),
  aliases: z.array(z.string()).optional(),
  subtype: z.string().optional(),
  nutrition_source: z.string().optional(),
  status: z.string().optional(),
  standard_class: z.string().optional(),
  components: z.record(z.string(), z.unknown()).optional(),
  ranges_wider: z.boolean().optional(),
  mandatory_report_line: z.string().optional(),
}});
export type MenuItem = z.infer<typeof menuItemSchema>;

export const dayMenuSchema = z.looseObject({{
  note: z.string().optional(),
  vegetables: z.array(z.string()).optional(),
}});
export type DayMenu = z.infer<typeof dayMenuSchema>;

export const bandStandardSchema = z.object({{
  kcal: z.object({{ direction: z.string(), value: z.number() }}),
  protein_g: z.object({{ direction: z.string(), value: z.number() }}),
}});
export type BandStandard = z.infer<typeof bandStandardSchema>;

export const captureFieldSchema = z.looseObject({{
  type: z.string().optional(),
  values: z.array(z.string()),
  note: z.string().optional(),
}});
export type CaptureField = z.infer<typeof captureFieldSchema>;

/** GET /menu — top-level keys are closed (main.menu()); nested yaml is open. */
export const menuSchema = z.object({{
  dishes: z.record(z.string(), menuItemSchema),
  days: z.record(z.string(), dayMenuSchema),
  bands: z.record(z.string(), bandStandardSchema),
  capture_fields: z.looseObject({{
    serving_style: captureFieldSchema,
    day: captureFieldSchema,
    band: captureFieldSchema,
  }}),
  remarks: z.array(z.string()),
  policy: policySchema,
}});
export type MenuResponse = z.infer<typeof menuSchema>;

/** GET /health */
export const healthSchema = z.object({{
  status: z.string(),
  phase: z.string(),
}});
export type HealthResponse = z.infer<typeof healthSchema>;
"""


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    text = generate()
    if "--write" in argv:
        OUT_PATH.write_text(text)
        print(f"wrote {OUT_PATH}")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
